CREATE TABLE `medicines` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`category` text NOT NULL,
	`name_of_medicine` text NOT NULL,
	`ema_product_number` text,
	`medicine_status` text,
	`opinion_status` text,
	`latest_procedure_affecting_product_information` text,
	`international_non_proprietary_name_inn_common_name` text NOT NULL,
	`active_substance` text NOT NULL,
	`therapeutic_area_mesh` text,
	`species_veterinary` text,
	`patient_safety` text,
	`atc_code_human` text,
	`atcvet_code_veterinary` text,
	`pharmacotherapeutic_group_human` text,
	`pharmacotherapeutic_group_veterinary` text,
	`therapeutic_indication` text,
	`accelerated_assessment` text,
	`additional_monitoring` text,
	`advanced_therapy` text,
	`biosimilar` text,
	`conditional_approval` text,
	`exceptional_circumstances` text,
	`generic_or_hybrid` text,
	`orphan_medicine` text,
	`prime_priority_medicine` text,
	`marketing_authorisation_developer_applicant_holder` text NOT NULL,
	`european_commission_decision_date` text,
	`start_of_rolling_review_date` text,
	`start_of_evaluation_date` text,
	`opinion_adopted_date` text,
	`withdrawal_of_application_date` text,
	`marketing_authorisation_date` text NOT NULL,
	`refusal_of_marketing_authorisation_date` text,
	`withdrawal_expiry_revocation_lapse_of_marketing_authorisation_date` text,
	`suspension_of_marketing_authorisation_date` text,
	`revision_number` text,
	`first_published_date` text,
	`last_updated_date` text NOT NULL,
	`medicine_url` text
);
